name: Release
on:
  push:
    branches: main
jobs:
  wrap-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            path: main

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
            repository: herbmc/DU-Orbital-Hud
            path: DU-Orbital-Hud

      - name: Version Number
        run: |
          echo "VERSION_NUMBER=$( date -u +%Y.%m.%d.%H%M.%S )" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NUMBER }}
          release_name: Release v${{ env.VERSION_NUMBER }}

      - name: Upload Autoconf as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above
          asset_path: main/pmai_flying_construct.conf
          asset_name: pmai_flying_construct.conf
          asset_content_type: text/yaml
